version: '3'
services:
  db:
    image: postgres
    container_name: reddy_22_server
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_DB=today
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
    name: reddy_22_database
